# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.codefornashville.org
title: Code For Nashville
email: webmaster@codefornashville.org
subTitle: Building Better Communities Through Technology
newMembersTitle: New Members

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

sections:
    - title: home
    - title: about
    - title: projects
    - title: team
    - title: contact

social:
  - title: twitter
    icon: twitter
    url: https://twitter.com/code4nashville
    header: true
  - title: github
    icon: github
    url: https://github.com/code-for-nashville
    header: true
  - title: meetup
    icon: calendar-o
    url: http://www.meetup.com/code-for-nashville
    header: true
  - title: slack
    icon: slack
    url: https://nashville-brigade-slackin.herokuapp.com
    header: true
  - title: facebook
    icon: facebook
    url: https://www.facebook.com/groups/codefornashville/
    header: false
  - title: google group
    icon: google-plus
    url: https://groups.google.com/forum/#!forum/code-for-nashville
    header: false
  - title: contact form
    icon: envelope-o
    url: /contact-form
    header: false

collections:
  - emeritus
  - projects
  - members
